### ISSUE TITLE
Frequent crashes.

### ISSUE THREAD

**Issue by faraddox** [azadix/D2Stats#19]
As i approached endgame in Median XL, i started to crash more and more frequently. I spent few days trying to find the cause, since i can no longer play for more than a few minutes. Tried d2gl (both dx and glide), tried without it, tried to run as admin (mxl launcher, d2 executables, d2stats) and with compatibility mode enabled. Until i finally decided to run without d2stats. And weirdly, i got no crashes. Was running cow levels (lvl 110) as benchmark, since mostly i crashed before even finishing it. Some random thoughts: it started closer to hell iirc. Most crashes i had happened on Firebear (may be just due to it being my mostly geared and fastest char). I had no crashes just staying in town for example. When game was crashing, in most cases there were items dropping at same moment nearby. At least 3 times i crased while hitting loot goblins. At least 2 while looting Writ's Leg. Sometimes, even if error message appeared, game would still respond to any input, i was able to play normally with only exception: d2stats wasn't working anymore, and any loot was hidden (even pressing ingame show loot button wouldn't work). Other times it would just freeze completely. But pressing OK always closed game even if it was still repsonding. 
Right now trying different combinations of options, most successfuls are on screenshot (3 cow runs without crashes, running more right now).
Some logs attached, may be it will help (forgot to save older ones when i was reinstalling game).
Both errors were always the same: same error code in access violation, same line and address in halt error.
At first i was using Zahariel's d2stats fork, and it was causing access violation error too (don't remember it causing halt error). Can't properly compare the frequency of crashes between these forks, since i was running low level areas back then, and much slower.
After all i was suggested to report an issue here too. You can find whole conversations and more screenshots in Median XL discord channel (#tech-support).
Edit: Attached my filter just in case, but i had even simplier filter when crashes appeared for the first time. Druid Skills rule was commented recently due to other issue i posted. And as update to situation - 6 runs total, no crashes with selected d2stats options and current filter.
Edit2: More than 10 runs with current setup, no crashes so far. Need some sleep, will check each option i disabled one by one later.
[f1.txt](https://github.com/user-attachments/files/17444459/f1.txt)

![image](https://github.com/user-attachments/assets/226f640d-a1e2-4698-930f-a8dfdf2d6abd)

[D2Debug-241019.txt](https://github.com/user-attachments/files/17444355/D2Debug-241019.txt)

![image](https://github.com/user-attachments/assets/7b7cdc0d-7c43-4e3f-bf34-161793b9fdf8)
![image](https://github.com/user-attachments/assets/dcfcef8a-c2f7-4517-8562-6c0199aeaaf1)
![image](https://github.com/user-attachments/assets/be5a6c8a-c66b-457d-8444-147dcf996d23)

**Comment by azadix** [comment]
Did some work in preparation for MXL 2.10. Can you check if the problems persist on https://github.com/azadix/D2Stats/tree/dev version? Just download the repo and run "Compile.bat" and let me know if something still happens. Can't really test what's happening but imo D2Stats causes some problem with MXL and in return MXL crashes D2Stats.
This version doesn't have "hide" and "show" keywords and no "Toggle items on ground" since that's being integrated into the game itself.
